// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

// ...
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQFiOpMzNNxbUpdUdJj3nHXA8TxTkcl-4',
    appId: '1:1028908244899:web:49ba14cb445dc8eac94416',
    messagingSenderId: '1028908244899',
    projectId: 'trivia-c4dab',
    authDomain: 'trivia-c4dab.firebaseapp.com',
    storageBucket: 'trivia-c4dab.firebasestorage.app',
    measurementId: 'G-4094KH5BXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy3FmRh2UbNgvHzifkA1Vdq1UORE2Fy64',
    appId: '1:1028908244899:android:d366e1281db382c6c94416',
    messagingSenderId: '1028908244899',
    projectId: 'trivia-c4dab',
    storageBucket: 'trivia-c4dab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS-reCj61onRgIWYsh-DoEsByvFOw2_Do',
    appId: '1:1028908244899:ios:30e06501f5c10053c94416',
    messagingSenderId: '1028908244899',
    projectId: 'trivia-c4dab',
    storageBucket: 'trivia-c4dab.firebasestorage.app',
    iosBundleId: 'com.mycompany.trivia2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS-reCj61onRgIWYsh-DoEsByvFOw2_Do',
    appId: '1:1028908244899:ios:1f7c24081c095695c94416',
    messagingSenderId: '1028908244899',
    projectId: 'trivia-c4dab',
    storageBucket: 'trivia-c4dab.firebasestorage.app',
    iosBundleId: 'com.example.trivia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQFiOpMzNNxbUpdUdJj3nHXA8TxTkcl-4',
    appId: '1:1028908244899:web:efb02788742648b8c94416',
    messagingSenderId: '1028908244899',
    projectId: 'trivia-c4dab',
    authDomain: 'trivia-c4dab.firebaseapp.com',
    storageBucket: 'trivia-c4dab.firebasestorage.app',
    measurementId: 'G-5SS2CCQDXJ',
  );
}

